export interface BugContext {
  url: string
  title: string
  userAgent: string
  viewport: { width: number; height: number }
  timestamp: string
  consoleErrors: string[]
}

export function buildBugIssueBody(
  description: string,
  context: BugContext,
  screenshotUrl: string | null,
): string {
  let pathname = context.url
  try { pathname = new URL(context.url).pathname } catch (_e) { /* use raw url as fallback */ }

  const lines: string[] = [
    '## Bug Report',
    '',
    `**Description:** ${description}`,
    '',
    '---',
    '',
    '## Environment',
    '',
    '| Field | Value |',
    '|-------|-------|',
    `| URL | \`${context.url}\` |`,
    `| Page Title | ${context.title} |`,
    `| Timestamp | ${context.timestamp} |`,
    `| Viewport | ${context.viewport.width}x${context.viewport.height} |`,
    `| User Agent | \`${context.userAgent}\` |`,
  ]

  if (context.consoleErrors.length > 0) {
    lines.push(
      '',
      '## Console Errors',
      '',
      '```',
      ...context.consoleErrors.map(e => e.replace(/`/g, "'")),
      '```',
    )
  }

  if (screenshotUrl) {
    lines.push(
      '',
      '## Screenshot',
      '',
      `![Bug screenshot](${screenshotUrl})`,
    )
  }

  lines.push(
    '',
    '---',
    '',
    '## For Claude Code Agent',
    '',
    'This issue was auto-generated by the in-app bug reporter.',
    `To investigate: check the page at \`${context.url}\`, review console errors above, and examine the screenshot.`,
    '',
    'Suggested steps:',
    `1. Identify the page component: look at \`app/pages/\` matching URL path \`${pathname}\``,
    '2. Reproduce the issue locally with `pnpm dev`',
    '3. Cross-reference console errors with server logs',
    '4. Check related server API routes in `server/api/`',
    '5. Fix, test, and commit',
  )

  return lines.join('\n')
}
